from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
import jwt
from ..core.config import settings

security = HTTPBearer()

def get_current_user_id(credentials: HTTPAuthorizationCredentials = Depends(security)) -> str:
    token = credentials.credentials
    try:
        # We don't necessarily need to verify the signature strictly here if we trust the API Gateway, 
        # but it's best practice. The Identity API signs it using JWT_SIGNING_KEY.
        # Note: .NET might use a specific encoding for the key, usually UTF-8 bytes.
        
        # In this simple implementation, we assume the token is signed with HS256
        # and the key is just the string.
        
        # Note: Since the JWT is generated by Identity API, let's decode it safely.
        # For full verification we would need the exact key bytes and algorithm (HS256).
        # We will decode without verification for now if the key is just a string without proper encoding format,
        # but let's try with verification first.
        
        payload = jwt.decode(
            token, 
            settings.JWT_SIGNING_KEY, 
            algorithms=["HS256"],
            audience=settings.JWT_AUDIENCE,
            issuer=settings.JWT_ISSUER
        )
        
        # The user ID is usually in the 'sub' or 'nameid' claim
        user_id = payload.get("sub") or payload.get("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")
        
        if user_id is None:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="User ID not found in token")
            
        return user_id
        
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Token has expired")
    except jwt.InvalidTokenError as e:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail=f"Invalid token: {e}")
