apiVersion: 1

contactPoints:
  - orgId: 1
    name: "Default Email"
    receivers:
      - uid: "default_email_receiver"
        type: "email"
        settings:
          addresses: "info@kiaricode.com, derciosinione@gmail.com"
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: "Default Email"
    group_by: ["alertname", "cluster", "service"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
