apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: "prom-ds"
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    uid: "loki-ds"
    url: http://loki:3100
  - name: Tempo
    type: tempo
    uid: "tempo-ds"
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: "prom-ds"
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: "loki-ds"
      tracesToLogs:
        datasourceUid: "loki-ds"
        filterByTraceId: true
        filterBySpanId: false
        mapTagNamesEnabled: false
      tracesToMetrics:
        datasourceUid: "prom-ds"
        tags: [{ key: 'service.name', value: 'service_name' }]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(traces_spanmetrics_latency_count{$$__tags}[5m]))'
